# Generated by Django 3.2 on 2021-06-08 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guitarra',
            name='imagen',
            field=models.ImageField(null=True, upload_to='guitarra'),
        ),
    ]
