# Generated by Django 3.2 on 2021-06-14 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_contacto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guitarra',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
